FROM ubuntu:20.04

USER root
WORKDIR /app

# install dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    # apt-utils nicht bei ns-3 Doku mit drin
    apt-utils \
    autoconf \
    bzr \
    ccache \
    cmake \
    cvs \
    g++ \
    #gi-cairo \
    git \
    libgsl-dev \
    libgtk-3-dev \
    libboost-dev \
    #libqt5-dev \
    mercurial \
    ninja-build \
    #pygraphviz \
    pkg-config \
    python3-dev \
    python3 \
    python3-pip \
    #qt5-dev-tools \
    sqlite3 \
    #unzip \ex
    unrar \
    wget 


# install ns3 & setting environment variables
RUN git clone https://gitlab.com/nsnam/bake 
RUN chmod +x ./bake/bake.py

ENV BAKE_HOME="/app/bake"
ENV PATH="${PATH}:${BAKE_HOME}"
ENV PYTHONPATH="${PYTHONPATH}:${BAKE_HOME}"

# copy deploy script into container an make it executable
COPY ./deploy.sh ./ 
RUN chmod u+x ./deploy.sh

CMD ["./deploy.sh"]